### ISSUE TITLE
zeda-chkdep is Installed twice at one command "make install" 

### ISSUE THREAD

**Issue by n-wakisaka** [zhidao/zeda#1]
$(CHKDEP) is installed again when $(TARGET) is installed.
https://github.com/zhidao/zeda/blob/f7908fc46d7f585a2fb363dd3f8e87c0d3b6b43b/app/makefile#L25-L29

I think the lines 26 and 27 are not required neccesarily.

**Comment by zhidao** [comment]
You are right! Corrected.
