### ISSUE TITLE
zeda-config-gen is not installed by "make install"

### ISSUE THREAD

**Issue by n-wakisaka** [zhidao/zeda#2]
My understanding is that the following command has to be run to install zeda-config-gen.
`$cd app && make config-gen`
https://github.com/zhidao/zeda/blob/c4e3ed42b6058b968502c85da312651053b41073/app/makefile#L13-L20

I suggest two ideas for installing zeda-config-gen with the only command "make install".
(i) remove lines 18 -- 20 and add `$(CONFIGGEN)` to line 25.
https://github.com/zhidao/zeda/blob/c4e3ed42b6058b968502c85da312651053b41073/app/makefile#L25-L27

(ii) add '&& make config-gen' to line 34 of zeda/makefile.
https://github.com/zhidao/zeda/blob/c4e3ed42b6058b968502c85da312651053b41073/makefile#L27-L34

**Comment by zhidao** [comment]
zeda-config-gen has to be installed in advance in order not to install zeda-config but to make it.
so, the process to install zeda-config-gen has to be separated from that to make (and install) apps.
a possible way to avoid a confusion is to change the target name config-gen to install-config-gen.
do you think it better?

**Comment by n-wakisaka** [comment]
I understand why the commands are separated.

I found that my local zeda/makefile was overwritten, so that zeda-config-gen was not installed by make command.

I'm sorry about my mistake.
Please disregard the issue.
